### ISSUE TITLE
Plugin fails to save settings, IntelliJ disables it and wants a restart

### ISSUE THREAD

**Issue by cedricziel** [dmarcotte/idea-handlebars#113] opened 2015-10-01 09:26 UTC
Basically it's like in the title. I edit a handlebars file, try to save it and the following error message appears:

``The plugin com.dmarcotte.handlebars failed to save settings and has been disabled. Please restart IntelliJ IDEA``

Afterwards i cannot open any hbs file anymore with the plugins' editor when I re-enable the hbs plugin.

I got it working again by randomly changing the files' content, my ``.idea`` - folder content and ``.IntelliJ14`` content in search for the mysterious, unsaveable - settings.

**Comment by dmarcotte** [comment] 2015-10-05 20:34
Thanks for the heads up on this @cedricziel.  Glad you were able to work around it.  Seems like this bad state can be due to a few factors (see some ideas here for instance: http://stackoverflow.com/questions/30040295/android-studio-unable-to-save-plugin-settings/30071697#30071697)

I'm going to optimistically close this as unrelated to the plugin, but if it happens again (big added bonus if you have steps to reproduce to get into this state) please let post again.

**Closed by dmarcotte** 2015-10-05 20:34 UTC
