### ISSUE TITLE
HBSv4.0.5 new partial syntax

### ISSUE THREAD

**Issue by JetAlex** [dmarcotte/idea-handlebars#116] opened 2016-01-25 17:05 UTC
Hello
http://handlebarsjs.com/partials.html
WebStorm doesnt understand several new constructions like: 
{{#*inline "myPartial"}}
...
{{/inline}}
and 
{{#> layout}}
...
Is it possible to add support for these tags?

**Comment by dmarcotte** [comment] 2016-02-03 01:21
Hey, thanks for the heads up @JetAlex.  Closing this as a dupe of https://youtrack.jetbrains.com/issue/WEB-19497, but rest assured this is going to get some attention soon.

**Closed by dmarcotte** 2016-02-03 01:21 UTC
