### ISSUE TITLE
Not compatible with PHPStorm 9.0.2

### ISSUE THREAD

**Issue by WanielDeiss** [dmarcotte/idea-handlebars#112] opened 2015-09-15 08:15 UTC
i can't use the plugin with PHPStrom 9.0.2 :cry: 

Error: Plugin is incompatible with this installation.

**Comment by anstarovoyt** [comment] 2015-09-16 22:41
Could you please attach a screenshot with the plugin in 'plugins' preferences?

**Comment by dmarcotte** [comment] 2015-10-05 20:37
@WanielDeiss going to close this since we were unable to reproduce, but if you're still stuck, please post the screenshot @anstarovoyt asked for and we'll do everything we can to get you up and running.

**Closed by dmarcotte** 2015-10-05 20:37 UTC
