### ISSUE TITLE
Compatibility with PhpStorm 2016.3.1

### ISSUE THREAD

**Issue by fullbl** [dmarcotte/idea-handlebars#124] opened 2016-12-15 09:54 UTC
Hi, I would like to update PhpStorm to newest version, but Handlebars/Mustache plugin seems to be uncompatible. Will it be updated?

Thanks!

**Comment by dmarcotte** [comment] 2016-12-21 19:55
Hey @fullbl, did this work itself out?  The plugin should definitely get updated and be compatible.  If checking for updates in the plugins preferences doesn't work, you can try restarting PhpStorm.

Going to optimistically close this, but please feel free to comment again if you're still in a bad state and we'll see if we can fix you up.

**Closed by dmarcotte** 2016-12-21 19:55 UTC

**Comment by timbonicus** [comment] 2017-01-03 21:25
The Handlebars plugin shows as incompatible with IntelliJ IDEA 2016.3.2 as well.

I upgraded IntelliJ to test this theory, and it does indeed get disabled. The Handlebars/Mustache version shows 163.9166.8.

**Comment by fullbl** [comment] 2017-01-04 11:06
To me version 163.9166.8 is working with PhpStorm 2016.3.2
Build #PS-163.10504.2, built on December 20, 2016


I just had to reassign file type *.hbs which was assigned to a generic "Handlebars" -- probably my fault

**Comment by dmarcotte** [comment] 2017-01-04 21:35
Thanks @fullbl, glad that's all worked out.

@timbonicus I was able to reproduce your problem in 2016.3.2.  Seems to be a bug in the upgrade... it's filed here (https://youtrack.jetbrains.com/issue/WEB-24821), and the workaround mentioned in the comments there worked for me:

**Workaround: uninstall and reinstall the plugin after upgrade to 2016.3.2**

Let me know if that doesn't fix things up for you and we'll see what else we can do.

**Comment by peterjmag** [comment] 2017-01-04 22:36
I had the same problem with RubyMine 2016.3.2. RubyMine 2017.1 EAP seems to be fine though (after prompting for a plugin upgrade to 171.1834.8).

**Comment by timbonicus** [comment] 2017-01-05 22:16
@dmarcotte Thanks, reinstalling the plugin worked for me in IntelliJ IDEA.
